### ISSUE TITLE
libbio-asn1-entrezgene-perl: Unescaped left brace in regex is deprecated

### ISSUE THREAD

**Issue by gregoa** [bioperl/Bio-ASN1-EntrezGene#2]
We have the following bug reported to the Debian package of
Bio-ASN1-EntrezGene (https://bugs.debian.org/826468):

It doesn't seem to be a bug in the packaging, so you may want to take
a look. Thanks!

------8<-----------8<-----------8<-----------8<-----------8<-----

```
Package: libbio-asn1-entrezgene-perl
Version: 1.700-1
Severity: normal
User: debian-perl@lists.debian.org
Usertags: perl-5.24-transition

Building this package triggers deprecation warnings with Perl 5.24
(currently in experimental), and probably with Perl 5.22 (current sid)
too.

  Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\G{ <-- HERE / at /<<PKGBUILDDIR>>/blib/lib/Bio/ASN1/EntrezGene.pm line 148.
  Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\G{ <-- HERE / at /<<PKGBUILDDIR>>/blib/lib/Bio/ASN1/Sequence.pm line 155.

The offending file is installed in a binary package, so this has
runtime effects as well. At least the bioperl package is affected.

A full build log is available at
  http://perl.debian.net/rebuild-logs/perl-5.24-throwaway/libbio-asn1-entrezgene-perl_1.700-1/
-- 
Niko Tyni   ntyni@debian.org


```

------8<-----------8<-----------8<-----------8<-----------8<-----

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by cjfields** [comment]
@gregoa Yes, seeing the same thing in core tests as well, it's a perl-specific warning.  Should be easy enough to fix.

```
...
t/SeqIO/entrezgene.t ................... Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\G{ <-- HERE / at /Users/cjfields/perl5/perlbrew/perls/perl-5.22.1/lib/site_perl/5.22.1/Bio/ASN1/EntrezGene.pm line 148.
```

**Comment by fjossandon** [comment]
@cjfields I think this is already fixed: https://github.com/bioperl/Bio-ASN1-EntrezGene/commit/a9b0183ab50ada69046aa4345e598ee41d61965b

**Comment by cjfields** [comment]
Yes, this is now fixed.  We'll push out a new release in the near future, the main issue I am waiting on (with this and other releases) is the impending changes to NCBI records to remove GI identifiers.
