### ISSUE TITLE
missing commit for release 1.73

### ISSUE THREAD

**Issue by carandraug** [bioperl/Bio-ASN1-EntrezGene#5]
There is a lightweight tag for release 1.73 but the commit itself is missing. I'll guess this is because `git push --tags` was used which pushes the tags but not the commit.

@cjfields do you happen to still have the clone used to make the release around? Can you push the missing commit(s)?

**Comment by cjfields** [comment]
Thanks for the heads-up @carandraug.  Yep, was on my old laptop in the office, just pushed.
